name: publish
permissions:
  id-token: write
  contents: read

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
      - run: npm install -g npm@11.6.1 # Ensure npm 11.5.1 or later is installed for OIDC
      - run: npm install
      - run: npm run check
      - run: npm publish --tag latest
